const char INDEX_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"pt-BR\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Dashboard</title><link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\"><style>body{background:#f5f7fa} .navbar{margin-bottom:1rem} .card{border-radius:.5rem;box-shadow:0 2px 8px rgba(0,0,0,.1)}</style></head><body>\n"
"<nav class=\"navbar navbar-expand-lg navbar-light bg-white shadow-sm\"><div class=\"container-fluid\"><a class=\"navbar-brand\" href=\"#\">MeteoStation</a><ul class=\"navbar-nav\"><li class=\"nav-item\"><a class=\"nav-link\" href=\"\\\">Dashboard</a></li><li class=\"nav-item\"><a class=\"nav-link\" href=\"\\temperatura\">Temperatura</a></li><li class=\"nav-item\"><a class=\"nav-link\" href=\"\\umidade\">Umidade</a></li><li class=\"nav-item\"><a class=\"nav-link\" href=\"\\pressao\">Pressão</a></li><li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\" href=\"#\">Configurações</a><ul class=\"dropdown-menu\"><li><a class=\"dropdown-item\" href=\"\\limites\">Limites</a></li><li><a class=\"dropdown-item\" href=\"\\offset\">Offsets</a></li></ul></li></ul></div></nav>\n"
"<div class=\"container\"><div class=\"row g-3\">\n"
" <div class=\"col-sm-6 col-lg-4\"><div class=\"card p-3 text-center\"><h6>AHT20 – Temp</h6><h2 id=\"val-temp-aht20\">-- °C</h2></div></div>\n"
" <div class=\"col-sm-6 col-lg-4\"><div class=\"card p-3 text-center\"><h6>BMP – Temp</h6><h2 id=\"val-temp-bmp\">-- °C</h2></div></div>\n"
" <div class=\"col-sm-6 col-lg-4\"><div class=\"card p-3 text-center\"><h6>Umidade</h6><h2 id=\"val-humidity\">-- %</h2></div></div>\n"
" <div class=\"col-sm-6 col-lg-4\"><div class=\"card p-3 text-center\"><h6>Pressão</h6><h2 id=\"val-pressure\">-- hPa</h2></div></div>\n"
" <div class=\"col-sm-6 col-lg-8\"><div class=\"card p-3\"><h6>Limites</h6><div class=\"row\">\n"
"  <div class=\"col\"><small>Temp Min/Max:</small><p id=\"lim-temp\">--/-- °C</p></div>\n"
"  <div class=\"col\"><small>Hum Min/Max:</small><p id=\"lim-hum\">--/-- %</p></div>\n"
" </div></div></div>\n"
" <div class=\"col-sm-6 col-lg-12\"><div class=\"card p-3\"><h6>Offsets</h6><div class=\"row\">\n"
"  <div class=\"col-md-4\"><small>Temperatura:</small><p id=\"offset-temp\">-- °C</p></div>\n"
"  <div class=\"col-md-4\"><small>Umidade:</small><p id=\"offset-hum\">-- %</p></div>\n"
"  <div class=\"col-md-4\"><small>Pressão:</small><p id=\"offset-press\">-- hPa</p></div>\n"
" </div></div></div>\n"
"</div></div>\n"
"<script>\n"
"async function fetchData(){let r=await fetch('/data');return r.ok?r.json():null;}\n"
"async function fetchSettings(){let r=await fetch('/settings/data');return r.ok?r.json():null;}\n"
"async function updateDashboard(){\n"
" let d=await fetchData(),s=await fetchSettings();if(!d||!s)return;\n"
" document.getElementById('val-temp-aht20').innerText=(d.temperature_aht20).toFixed(1)+' °C';\n"
" document.getElementById('val-temp-bmp').innerText=(d.temperature_bmp).toFixed(1)+' °C';\n"
" document.getElementById('val-humidity').innerText=(d.humidity).toFixed(1)+' %';\n"
" document.getElementById('val-pressure').innerText=(d.pressure).toFixed(1)+' hPa';\n"
" document.getElementById('lim-temp').innerText=`${s.tempMin}/${s.tempMax} °C`;\n"
" document.getElementById('lim-hum').innerText=`${s.humMin}/${s.humMax} %`;\n"
" document.getElementById('offset-temp').innerText=`${s.offsetTemp} °C`;\n"
" document.getElementById('offset-hum').innerText=`${s.offsetHum} %`;\n"
" document.getElementById('offset-press').innerText=`${s.offsetPres} hPa`;\n"
"}\n" 
"updateDashboard();setInterval(updateDashboard,2000);\n"
"</script>\n"
"</body></html>"
;