const char OFFSET_HTML[] =
"<!DOCTYPE html>"
"<html lang=\"pt-BR\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Offsets</title><link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\"><style>body{background:#f5f7fa}.navbar{margin-bottom:1rem}.form-control,.btn{border-radius:.25rem}</style></head><body>"
"<nav class=\"navbar navbar-expand-lg navbar-light bg-white shadow-sm\"><div class=\"container-fluid\"><a class=\"navbar-brand\" href=\"#\">MeteoStation</a><ul class=\"navbar-nav\"><li class=\"nav-item\"><a class=\"nav-link\" href=\"\\\">Dashboard</a></li><li class=\"nav-item\"><a class=\"nav-link\" href=\"\\temperatura\">Temperatura</a></li><li class=\"nav-item\"><a class=\"nav-link\" href=\"\\umidade\">Umidade</a></li><li class=\"nav-item\"><a class=\"nav-link\" href=\"\\pressao\">Pressão</a></li><li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\" href=\"#\">Configurações</a><ul class=\"dropdown-menu\"><li><a class=\"dropdown-item\" href=\"\\limites\">Limites</a></li><li><a class=\"dropdown-item active\" href=\"\\offset\">Offsets</a></li></ul></li></ul></div></nav>"
"<div class=\"container\"><form id=\"f2\" class=\"row g-3\">"
" <div class=\"col-md-4\"><label for=\"offsetTemp\" class=\"form-label\">Offset Temperatura (°C)</label><input id=\"offsetTemp\" class=\"form-control\" type=\"number\" step=\"0.1\" placeholder=\"Ex: 0.0\" required></div>"
" <div class=\"col-md-4\"><label for=\"offsetHum\" class=\"form-label\">Offset Umidade (%)</label><input id=\"offsetHum\" class=\"form-control\" type=\"number\" step=\"0.1\" placeholder=\"Ex: 0.0\" required></div>"
" <div class=\"col-md-4\"><label for=\"offsetPres\" class=\"form-label\">Offset Pressão (hPa)</label><input id=\"offsetPres\" class=\"form-control\" type=\"number\" step=\"0.1\" placeholder=\"Ex: 0.0\" required></div>"
" <div class=\"col-12\"><button class=\"btn btn-primary w-100\" type=\"submit\">Salvar Configurações</button></div>"
"</form></div>"
"<script>"
"async function fetchSettings(){let r=await fetch('/settings/data');return r.ok?r.json():null;}"
"async function saveSettings(p){console.log('Salvando configurações:', p);await fetch('/settings/offset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});}"
"window.addEventListener('load',async()=>{let s=await fetchSettings();if(!s)return;['offsetTemp','offsetHum','offsetPres'].forEach(id=>document.getElementById(id).value=s[id])});"
"document.getElementById('f2').addEventListener('submit',async e=>{e.preventDefault();let s=await fetchSettings(),p={offsetTemp:parseFloat(offsetTemp.value),offsetHum:parseFloat(offsetHum.value),offsetPres:parseFloat(offsetPres.value)};await saveSettings(p);alert('Salvo')});"
"</script>"
"<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>"
"</body></html>"
;
